app = "vixpythonproxy"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "python:3.11-slim"

[env]
  PORT = "8080"
  PROXY_TIMEOUT = "15"

[experimental]
  allowed_public_ports = []

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443

  [services.tcp_checks]
    interval = 10000
    timeout = 2000
    restart_limit = 6
